### ISSUE TITLE
Perform clustering without ground-truth?

### ISSUE THREAD

**Issue by ShankarChavan** [FlorentF9/DeepTemporalClustering#1]
Can you share a sample code of using DTC which doesn't have ground-truth in the data?
i.e. we have unlabeled dataset and we need to cluster them

**Comment by FlorentF9** [comment]
Hi, unfortunately I am just seeing this issue now. Labels are completely optional and only used to evaluate external metrics (accuracy etc.). Just use `None` for `y_train` and `y_val`.
