### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by chen-ya-ling** [FlorentF9/DeepTemporalClustering#11]
Hello, I have an assertion error when I run your code. I don't know how to modify it, and I don't know the function of this assertion. Can you explain it?

**Comment by FlorentF9** [comment]
It is probably caused by the `assert(timesteps % pool_size == 0)`, meaning that the pooling size must divide the number of timesteps of the input. You need to set the pool_size parameter accordingly.

**Comment by chen-ya-ling** [comment]
Thank you for your reply! I've reset the pool_ Size, after running again, there is no problem.

**Comment by loovi7** [comment]
> Thank you for your reply! I've reset the pool_ Size, after running again, there is no problem.

I want to know how you reset it , could you help me?

**Comment by FlorentF9** [comment]
Either as a command-line argument ̀`--pool_size` if running the main script, or as an argument `pool_size=...`when instantiating the DTC model class.

**Comment by precipitation0224** [comment]
Hello, when I run the main script with "%run DeepTemporalClustering.py --pool_size 2", it has an attributeError, 'Node' object has no attribute 'output_masks', Can you help solve it? Thanks.
