### ISSUE TITLE
CuDNNLSTM not found

### ISSUE THREAD

**Issue by genesfa** [FlorentF9/DeepTemporalClustering#15]
Hey,

actually I'm using the newest Version of Keras (2.4.0) and Tensorflow (2.4), in this case I can’t load CuDNNLSTM (TAE.py).

I also tried to install an older version of Keras (2.3.0) and Tensorflow which includes CuDNNLSTM, but in this case there are new errors as well. 

Can you create a new Requirements.txt which include all libraries with their specific version you use. 

I hope you can help me

**Comment by FlorentF9** [comment]
It was using Keras 2.2.2 and Tensorflow 1.9.0. It seems like CuDNNLSTM does not exist anymore and has been superseded by LSTM. Can you try using the LSTM class instead? When I have some time I need to bring all this up-to-date.

**Comment by nnbaokhang** [comment]
Verified that change CuDNNLSTM  to LSTM works for me!

**Comment by FlorentF9** [comment]
Closing this issue for now.
