### ISSUE TITLE
Heatmap use

### ISSUE THREAD

**Issue by jtremblayTelmatik** [FlorentF9/DeepTemporalClustering#20]
Could you please explain how to visualize the heatmap weights on a time series ?

**Comment by jtremblayTelmatik** [comment]
Say that I have a number of 1d time series of equal length L and that I want to divide them into k clusters. I understand that I can use h = dtc.heatmap_model.predict(X_train)[1] to obtain a array of shape [L, k]. How do I interpret these results ? Thank you !

**Comment by FlorentF9** [comment]
The array h[:, k] is the class activation map for cluster k, meaning that each element represents the contribution of this time step to being assigned to cluster k. Please also see [this issue](https://github.com/FlorentF9/DeepTemporalClustering/issues/12) where I gave some explanation on the heatmap.

Note that the heatmap network is not necessary to perform the clustering, it is a tool for results explainability.
