### ISSUE TITLE
assert(timesteps % pool_size == 0) AssertionError

### ISSUE THREAD

**Issue by yyhhhjnjvgcx** [FlorentF9/DeepTemporalClustering#26]
Namespace(dataset='CBF', ae_weights=None, n_clusters=None, n_filters=50, kernel_size=10, strides=1, pool_size=10, n_units=[50, 1], gamma=1.0, alpha=1.0, dist_metric='eucl', cluster_init='kmeans', heatmap=False, pretrain_epochs=10, epochs=100, eval_epochs=1, save_epochs=10, batch_size=64, tol=0.001, patience=5, finetune_heatmap_at_epoch=8, initial_heatmap_loss_weight=0.1, final_heatmap_loss_weight=0.9, save_dir='results/tmp')
Traceback (most recent call last):
  File "D:\PycharmProjects\20220213\kshape\DCN\4.py", line 498, in <module>
    dtc = DTC(n_clusters=args.n_clusters,
  File "D:\PycharmProjects\20220213\kshape\DCN\4.py", line 55, in __init__
    assert(timesteps % pool_size == 0)
AssertionError
How to solve？thanks

**Comment by FlorentF9** [comment]
Pooling size must divide the number of timesteps in the input. CBF dataset has 128 timesteps so pool_size=8 would work.
I just changed this default value to pool_size=8 in the main script to prevent this error!
